# Generated by Django 4.2 on 2023-05-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothesApi', '0003_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(),
        ),
    ]
