# Generated by Django 4.2 on 2023-05-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothesApi', '0005_alter_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='season',
            field=models.CharField(default='spring', max_length=60),
            preserve_default=False,
        ),
    ]
