# Generated by Django 4.2 on 2023-05-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothesApi', '0006_item_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='season',
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='display_size',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='display_type',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='operating_system',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='production_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='ram',
            field=models.IntegerField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='storage',
            field=models.IntegerField(blank=True, max_length=80, null=True),
        ),
    ]
